# security.yaml
security:
    password_hashers:
        App\Entity\Educateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Educateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /dashboard   # Redirection après la connexion réussie

            logout:
                path: app_logout


    access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # ...
