security:
    encoders:
        App\Entity\Educateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Educateur
                property: email

    firewalls:
        main:
            pattern: ^/
            anonymous: lazy
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_homepage

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
